# DejaVu Desktop — compositeur (ombres + transparence légère)
backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 14;
shadow-opacity = 0.5;
shadow-offset-x = -10;
shadow-offset-y = -6;
shadow-exclude = [
  "class_g = 'tint2'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

corner-radius = 6;
rounded-corners-exclude = [
  "class_g = 'tint2'",
  "window_type = 'dock'"
];

fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;

opacity-rule = [
  "95:class_g = 'jgmenu'"
];
